import {describe,it,expect} from 'vitest';
import {analyzeHeartRate,hrPeers,matchedEffort,normalizeStreams,resolveZones,settingsError,sourceZones,type HrSettings,type HrStream} from '../src/health/heart-rate';
import type {TrainingSession} from '../src/repositories/activities';
const settings:HrSettings={subject_id:'fixture',sport:'all',method:'max',max_hr:200,rest_hr:null,date_of_birth:null,custom_edges:null};
const activity=(id:string,date='2026-08-01'):TrainingSession=>({id,physiological_date:date,activity_type:'Ride',provider:'intervals_icu',started_at:date+'T08:00:00Z',ended_at:date+'T09:00:00Z',source_device:null,source_record_id:null,external_session_id:null,distance_m:30000,elevation_gain_m:300,active_energy_kcal:null,avg_heart_rate_bpm:140,max_heart_rate_bpm:170});
describe('Heart rate references',()=>{
 it('uses personal max before source and never adopts an activity peak',()=>{expect(resolveZones(settings,{athlete_max_hr:180,max_heartrate:230},'2026-01-01')?.edges).toEqual([100,120,140,160,180,200]);expect(resolveZones(null,{max_heartrate:180},'2026-01-01')).toBeNull();});
 it('labels source reference and adult age estimates',()=>{expect(resolveZones(null,{athlete_max_hr:190},'2026-01-01')?.estimated).toBe(true);expect(resolveZones({...settings,max_hr:null,date_of_birth:'1986-01-01'},null,'2026-01-01')?.max).toBe(180);expect(resolveZones({...settings,max_hr:null,date_of_birth:'2016-01-01'},null,'2026-01-01')).toBeNull();});
 it('uses birthday at activity date and refuses missing age',()=>{expect(resolveZones({...settings,max_hr:null,date_of_birth:'1986-12-01'},null,'2026-01-01')?.max).toBe(180.7);expect(resolveZones(null,null,'2026-01-01')).toBeNull();});
 it('validates reserve inputs and custom boundaries',()=>{expect(settingsError({...settings,method:'reserve'})).toBeTruthy();expect(resolveZones({...settings,method:'reserve',rest_hr:50},null,'2026-01-01')?.edges).toEqual([125,140,155,170,185,200]);expect(settingsError({...settings,method:'custom',custom_edges:[90,110,110,150,170,190]})).toBeTruthy();});
 it('retains origin upper bounds without reallocating counts to personal zones',()=>{const z=sourceZones({icu_hr_zones:[120,150,190],icu_hr_zone_times:[100,200,300]});expect(z?.[1]).toEqual({label:'Z2',range:'>120–150 bpm',seconds:200});expect(sourceZones({icu_hr_zones:[120,150],icu_hr_zone_times:[200]})).toBeNull();});
});
describe('Heart rate curves',()=>{
 it('rejects unsorted and mismatched streams without inventing time',()=>{expect(normalizeStreams([{type:'time',data:[0,0]},{type:'heartrate',data:[100,110]}])).toBeNull();expect(normalizeStreams([{type:'time',data:[0,1,2]},{type:'heartrate',data:[100,110]}])).toBeNull();expect(normalizeStreams([{type:'heartrate',data:[100,110]}])).toBeNull();});
 it('weights irregular samples and excludes gaps, missing and implausible HR',()=>{const s=normalizeStreams([{type:'time',data:[0,2,10,30,31,32]},{type:'heartrate',data:[100,150,180,null,999,120]}])!;const a=analyzeHeartRate(s,null);expect(a.observed).toBe(10);expect(a.mean).toBe(140);expect(a.coverage).toBe(10/32);});
 it('counts boundaries exactly once including above max',()=>{const z=resolveZones(settings,null,'2026-01-01');const s:HrStream={time:[0,1,2,3,4,5,6,7,8],heartrate:[99,100,120,140,160,180,200,201,210]};const a=analyzeHeartRate(s,z);expect(a.times).toEqual([1,1,1,1,1,2,1]);expect(a.times.reduce((x,y)=>x+y,0)).toBe(a.observed);});
 it('clips selection intervals without filling the final sample',()=>{const a=analyzeHeartRate({time:[0,5,10],heartrate:[100,150,200]},null,3,8);expect(a.observed).toBe(5);expect(a.mean).toBe(130);expect(a.peak).toBe(150);});
 it('requires three minutes common work after warmup',()=>{const s=(hr:number):HrStream=>({time:Array.from({length:1001},(_,i)=>i),heartrate:Array(1001).fill(hr),watts:Array(1001).fill(210)});const rows=matchedEffort(s(140),s(150),'power');expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({low:200,high:225,a:140,b:150,aSeconds:400,bSeconds:400});expect(matchedEffort({...s(140),watts:undefined},s(150),'power')).toEqual([]);});
});
describe('Comparable cardiac effort',()=>{
 it('excludes future, different sport, unmatched effort and estimated power',()=>{const current=activity('now','2026-09-01'),past=activity('past'),future=activity('future','2026-09-02'),run={...activity('run'),activity_type:'Run'};const data=new Map([current,past,future,run].map(s=>[s.id,{icu_average_watts:200,device_watts:true,average_speed:8}]));expect(hrPeers(current,[past,future,run],data,'power').map(x=>x.session.id)).toEqual(['past']);data.set('past',{icu_average_watts:200,device_watts:false,average_speed:8});expect(hrPeers(current,[past],data,'power')).toEqual([]);});
 it('does not force a match with missing elevation or distant duration',()=>{const current=activity('now','2026-09-01');const past={...activity('past'),elevation_gain_m:null};const data=new Map([['now',{average_speed:8}],['past',{average_speed:8}]]);expect(hrPeers(current,[past],data,'speed')).toEqual([]);});
 it('respects source ignore flags',()=>{const current=activity('now','2026-09-01'),past=activity('past');const data=new Map([['now',{average_speed:8}],['past',{average_speed:8,icu_ignore_hr:true}]]);expect(hrPeers(current,[past],data,'speed')).toEqual([]);});
});
