import type { ValidationCase } from './types';

export const retrospectiveCasesV1: ValidationCase[] = [
  {
    caseId: 'RV-001',
    title: 'High-load mountain block',
    status: 'draft',
    datasetRole: 'development',
    episodeStart: 'TBD',
    episodeEnd: 'TBD',
    evaluationWindowBeforeDays: 2,
    evaluationWindowAfterDays: 7,
    controlWindowDays: 21,
    knownFacts: [],
    expectedObservables: [
      {
        metricKey: 'training_load',
        direction: 'increase',
        horizon: 'during',
        required: true,
        rationale: 'Known unusually demanding multi-day training episode.',
      },
      {
        metricKey: 'hrv_rmssd',
        direction: 'decrease',
        horizon: 'after',
        required: false,
        rationale: 'Recovery response is plausible but not guaranteed.',
      },
      {
        metricKey: 'resting_heart_rate',
        direction: 'increase',
        horizon: 'after',
        required: false,
        rationale: 'Recovery response is plausible but not guaranteed.',
      },
    ],
    excludedClaims: ['The episode caused any observed recovery change.'],
    relevantMetrics: ['training_load', 'hrv_rmssd', 'resting_heart_rate'],
    relevantFindings: ['acute_training_load_increase', 'recovery_load_mismatch', 'sustained_hrv_drop', 'sustained_rhr_elevation'],
    minimumCoverageByMetric: {},
    confounders: ['sleep', 'illness', 'alcohol', 'travel', 'heat', 'altitude'],
    requireSourceContinuityForMetrics: ['hrv_rmssd', 'resting_heart_rate'],
    caseVersion: '1.0.0',
  },
  {
    caseId: 'RV-002',
    title: 'Wearable-off gap',
    status: 'draft',
    datasetRole: 'validation',
    episodeStart: 'TBD',
    episodeEnd: 'TBD',
    evaluationWindowBeforeDays: 0,
    evaluationWindowAfterDays: 0,
    controlWindowDays: 14,
    knownFacts: [],
    expectedObservables: [
      {
        metricKey: 'hrv_rmssd',
        direction: 'absent',
        horizon: 'during',
        required: true,
        rationale: 'No wearable data should remain a gap and must not be imputed.',
      },
    ],
    excludedClaims: ['The device-not-worn reason is inferred without explicit evidence.'],
    relevantMetrics: ['hrv_rmssd', 'resting_heart_rate', 'sleep_duration'],
    relevantFindings: ['insufficient_recent_data'],
    minimumCoverageByMetric: {},
    confounders: [],
    requireSourceContinuityForMetrics: [],
    caseVersion: '1.0.0',
  },
];
