import type { FindingRegistryEntryV1 } from './types';
const B='Detecta una desviación longitudinal reproducible. No establece por sí sola causa, diagnóstico ni recomendación médica.';
export const FINDING_REGISTRY_V1:Record<string,FindingRegistryEntryV1>={
 sustained_hrv_drop:{findingKey:'sustained_hrv_drop',domain:'recovery',title:'HRV sostenidamente inferior a tu referencia',description:'Mediana reciente de HRV por debajo del baseline personal con cobertura suficiente.',inputMetrics:['hrv_rmssd'],recentWindowDays:7,baselineWindowDays:42,minimumRecentSamples:4,minimumBaselineSamples:20,confounders:['illness','training_load','alcohol','travel','sleep','source_transition'],interpretationBoundary:B,detectorVersion:'sustained_hrv_drop_v2'},
 sustained_rhr_elevation:{findingKey:'sustained_rhr_elevation',domain:'recovery',title:'FC de reposo sostenidamente superior a tu referencia',description:'FC de reposo reciente elevada frente al baseline personal.',inputMetrics:['resting_heart_rate'],recentWindowDays:7,baselineWindowDays:42,minimumRecentSamples:4,minimumBaselineSamples:20,confounders:['illness','training_load','alcohol','travel','sleep','heat','source_transition'],interpretationBoundary:B,detectorVersion:'sustained_rhr_elevation_v1'},
 recovery_concordance:{findingKey:'recovery_concordance',domain:'recovery',title:'Marcadores de recuperación desplazados de forma concordante',description:'HRV inferior y FC de reposo superior simultáneamente.',inputMetrics:['hrv_rmssd','resting_heart_rate'],recentWindowDays:7,baselineWindowDays:42,minimumRecentSamples:4,minimumBaselineSamples:20,confounders:['illness','training_load','alcohol','travel','sleep','source_transition'],interpretationBoundary:B,detectorVersion:'recovery_concordance_v1'},
 sleep_deficit:{findingKey:'sleep_deficit',domain:'sleep',title:'Sueño reciente inferior a tu referencia',description:'Duración de sueño reciente inferior al baseline personal.',inputMetrics:['sleep_duration'],recentWindowDays:7,baselineWindowDays:42,minimumRecentSamples:4,minimumBaselineSamples:20,confounders:['travel','late_dinner','alcohol','illness','source_transition'],interpretationBoundary:B,detectorVersion:'sleep_deficit_v1'},
 acute_training_load_increase:{findingKey:'acute_training_load_increase',domain:'training',title:'Aumento reciente de carga de entrenamiento',description:'La carga reciente ha aumentado frente a la referencia de entrenamiento.',inputMetrics:['training_load'],recentWindowDays:7,baselineWindowDays:28,minimumRecentSamples:1,minimumBaselineSamples:8,confounders:['sport_mix','source_transition'],interpretationBoundary:'Describe cambio de carga. No convierte un ratio en una zona clínica de seguridad o riesgo.',detectorVersion:'acute_training_load_increase_v1'},
 recovery_load_mismatch:{findingKey:'recovery_load_mismatch',domain:'training_recovery',title:'Carga y recuperación se desplazan en direcciones opuestas',description:'Aumento de carga junto con desplazamiento desfavorable de HRV y/o FC de reposo.',inputMetrics:['training_load','hrv_rmssd','resting_heart_rate'],recentWindowDays:7,baselineWindowDays:42,minimumRecentSamples:4,minimumBaselineSamples:20,confounders:['illness','sleep','alcohol','travel','source_transition'],interpretationBoundary:B,detectorVersion:'recovery_load_mismatch_v1'},
 weight_trend:{findingKey:'weight_trend',domain:'body',title:'Cambio sostenido de tendencia de peso',description:'Tendencia de varias semanas, no oscilación diaria aislada.',inputMetrics:['weight'],recentWindowDays:28,baselineWindowDays:90,minimumRecentSamples:4,minimumBaselineSamples:8,confounders:['hydration','measurement_device','time_of_day'],interpretationBoundary:B,detectorVersion:'weight_trend_v1'},
 spo2_deviation:{findingKey:'spo2_deviation',domain:'respiratory',title:'SpO₂ inferior a tu distribución habitual',description:'Desviación longitudinal de SpO₂ respecto de referencia personal.',inputMetrics:['oxygen_saturation'],recentWindowDays:7,baselineWindowDays:42,minimumRecentSamples:4,minimumBaselineSamples:20,confounders:['altitude','illness','sensor_quality','source_transition'],interpretationBoundary:'Detecta desviación personal. No diagnostica apnea, hipoxemia ni enfermedad.',detectorVersion:'spo2_deviation_v1'},
 insufficient_recent_data:{findingKey:'insufficient_recent_data',domain:'data_quality',title:'Datos recientes insuficientes',description:'Cobertura insuficiente para sostener inferencias longitudinales recientes.',inputMetrics:[],recentWindowDays:7,minimumRecentSamples:0,confounders:['device_not_worn','source_not_synced','permission_missing','unknown'],interpretationBoundary:'Es un hallazgo de calidad de datos, no fisiológico.',detectorVersion:'insufficient_recent_data_v1'},
 source_discontinuity:{findingKey:'source_discontinuity',domain:'data_quality',title:'Cambio de fuente de medición',description:'Cambio de dispositivo/proveedor potencialmente relevante para comparabilidad longitudinal.',inputMetrics:[],recentWindowDays:1,minimumRecentSamples:0,confounders:[],interpretationBoundary:'Señala posible discontinuidad metrológica; no implica un cambio fisiológico.',detectorVersion:'source_discontinuity_v1'}
};
