import {useEffect,useMemo,useRef,useState} from 'react';
import {useSubject} from '../subjects/SubjectProvider';
import type {TrainingSession} from '../repositories/activities';
import {getHrSettings,getHrSources,getHrStream,importHrStream} from '../repositories/heart-rate';
import {analyzeHeartRate,hrNumber,hrTime,hrPeers,matchedEffort,resolveZones,sourceZones,type HrSettings,type HrStream} from '../health/heart-rate';
import {numberLabel} from '../health/activities';
import HeartRateSettings from './HeartRateSettings';
import './heart-rate.css';
const colors=['#a2ada4','#61977b','#7faa6e','#c3a34b','#cb7c46','#b44e49','#803d55'];
export default function ActivityHeartRate({session,sessions,source,userId}:{session:TrainingSession;sessions:TrainingSession[];source:Record<string,unknown>|null;userId:string}){
  const {scope}=useSubject();return scope?<HeartRate key={`${scope.subjectId}:${session.id}`} subjectId={scope.subjectId} canImport={['admin','owner','editor'].includes(scope.permission)} session={session} sessions={sessions} source={source} userId={userId}/>:null;
}
export function HeartRate({subjectId,canImport,session,sessions,source,userId}:{subjectId:string;canImport:boolean;session:TrainingSession;sessions:TrainingSession[];source:Record<string,unknown>|null;userId:string}){
  const [settings,setSettings]=useState<HrSettings[]>([]),[stream,setStream]=useState<HrStream|null>(null),[sources,setSources]=useState(new Map<string,Record<string,unknown>>()),[status,setStatus]=useState('Cargando datos de FC…'),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[mode,setMode]=useState<'power'|'speed'>('speed'),[peerId,setPeerId]=useState(''),[peerStream,setPeerStream]=useState<HrStream|null>(null),[from,setFrom]=useState(0),[to,setTo]=useState(100),[cursor,setCursor]=useState(0);
  const latestPeer=useRef(peerId);latestPeer.current=peerId;
  useEffect(()=>{const listener=(e:Event)=>{if((e as CustomEvent).detail===subjectId)setRevision(r=>r+1);};window.addEventListener('healthos-hr-settings',listener);return()=>window.removeEventListener('healthos-hr-settings',listener);},[subjectId]);
  useEffect(()=>{let active=true;Promise.allSettled([getHrSettings(subjectId),getHrStream(subjectId,session.id),getHrSources(userId)]).then(([a,b,c])=>{if(!active)return;if(a.status==='fulfilled')setSettings(a.value);if(b.status==='fulfilled')setStream(b.value);if(c.status==='fulfilled')setSources(new Map(sessions.flatMap(s=>s.provider==='intervals_icu'&&s.source_record_id&&c.value.get(s.source_record_id)?.external_id===s.external_session_id?[[s.id,c.value.get(s.source_record_id)!] as const]:[])));setStatus([a,b,c].some(r=>r.status==='rejected')?'Parte de los datos de FC no se pudo cargar. No se aplicarán conclusiones sobre esos datos.':'');});return()=>{active=false;};},[subjectId,session.id,userId,revision,sessions]);
  const chosen=settings.find(s=>s.sport===session.activity_type)??settings.find(s=>s.sport==='all')??null;
  const zones=resolveZones(chosen,source,session.physiological_date);
  const end=stream?.time.at(-1)??0;
  const result=useMemo(()=>stream?analyzeHeartRate(stream,zones,end*from/100,end*to/100):null,[stream,zones?.edges.join(','),end,from,to]);
  const original=sourceZones(source),originalTotal=original?.reduce((sum,z)=>sum+z.seconds,0)??0;
  const allSources=new Map(sources);if(source)allSources.set(session.id,source);
  const peers=hrPeers(session,sessions,allSources,mode),peer=peers.find(p=>p.session.id===peerId);
  useEffect(()=>{let active=true;setPeerStream(null);if(peerId)getHrStream(subjectId,peerId).then(s=>{if(active)setPeerStream(s);}).catch(()=>{if(active)setStatus('No se pudo cargar la curva de comparación.');});return()=>{active=false;};},[peerId,subjectId]);
  const fetchStream=async(id:string)=>{setBusy(true);setStatus('Consultando las series de Intervals…');try{const result=await importHrStream(subjectId,id);if(id===session.id)setStream(result.stream);else if(latestPeer.current===id)setPeerStream(result.stream);setStatus(result.message||(!result.stream?'La fuente no ha entregado una curva de FC utilizable.':''));}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}};
  const rows=result&&zones?[{label:'Bajo Z1',range:`<${zones.edges[0]} bpm`,seconds:result.times[0]},...Array.from({length:5},(_,i)=>({label:`Z${i+1}`,range:`${zones.edges[i]}–${i<4?'<':''}${zones.edges[i+1]} bpm`,seconds:result.times[i+1]})),{label:'Sobre Z5',range:`>${zones.edges[5]} bpm`,seconds:result.times[6]}]:original;
  const total=result&&zones?result.observed:originalTotal;
  const dominant=rows?.reduce((best,row)=>row.seconds>best.seconds?row:best,rows[0]);
  const bands=stream&&peerStream?matchedEffort(stream,peerStream,mode):[];
  const selectedPoint=stream?Math.min(stream.time.length-1,Math.round(cursor/100*(stream.time.length-1))):0;
  const ignored=source?.icu_ignore_hr===true;
  if(ignored)return <section className="activityHr"><h2>Frecuencia cardíaca</h2><p role="alert">La fuente marca la FC de esta actividad para ignorar. No se calculan zonas ni comparaciones con esta señal. Revisa el registro en origen.</p><HeartRateSettings sport={session.activity_type}/></section>;
  return <section className="activityHr"><header><div className="eyebrow">RESPUESTA CARDÍACA</div><h2>El esfuerzo, latido a latido</h2><p>FC durante la sesión, distribución del tiempo y comparación a trabajo externo parecido.</p></header>
    {ignored&&<p role="alert">La fuente marca la FC de esta actividad para ignorar. Revisa la señal antes de interpretar sus valores.</p>}
    <div className="hrStats"><div><small>FC media · resumen de origen</small><strong>{numberLabel(session.avg_heart_rate_bpm,'bpm')}</strong></div><div><small>Pico registrado · no es tu FC máxima personal</small><strong>{numberLabel(session.max_heart_rate_bpm,'bpm')}</strong></div><div><small>Referencia para zonas</small><strong>{zones?.max?numberLabel(zones.max,'bpm'):'Sin máxima'}</strong><small>{zones?.label??'Configura una referencia personal'}</small></div></div>
    <HeartRateSettings sport={session.activity_type}/>
    {!stream?<div className="hrEmpty"><h3>Curva temporal</h3><p>El resumen no permite conocer cuándo subió la FC ni cómo cambió a lo largo del esfuerzo. Podemos solicitar la serie a la fuente; su disponibilidad depende de la actividad y de los permisos de origen.</p>{canImport&&session.provider==='intervals_icu'&&<button disabled={busy} onClick={()=>fetchStream(session.id)}>Obtener curva de FC</button>}</div>:<>
      <div className="hrChartHead"><h3>FC a lo largo de la actividad</h3><span>{result?Math.round(result.coverage*100):0} % del tramo con FC utilizable</span></div>
      <HeartRateChart stream={stream} zones={zones?.edges??[]} from={end*from/100} to={end*to/100}/>
      <div className="hrRange"><label>Inicio del análisis · {Math.round(end*from/6000)} min<input type="range" min="0" max="99" value={from} onChange={e=>setFrom(Math.min(Number(e.target.value),to-1))}/></label><label>Fin del análisis · {Math.round(end*to/6000)} min<input type="range" min="1" max="100" value={to} onChange={e=>setTo(Math.max(Number(e.target.value),from+1))}/></label></div>
      <label className="hrCursor">Explorar la curva<input type="range" min="0" max="100" value={cursor} onChange={e=>setCursor(Number(e.target.value))}/></label><p className="hrPoint">Minuto {(stream.time[selectedPoint]/60).toFixed(1)} · {numberLabel(stream.heartrate[selectedPoint],'bpm')} · {numberLabel(stream.watts?.[selectedPoint],'W')} · {numberLabel((stream.velocity_smooth?.[selectedPoint]??0)*3.6||null,'km/h')}</p>
      <p className="hrExplanation">En el tramo seleccionado hay {hrTime(result!.observed)} de FC utilizable, con media ponderada por tiempo de {numberLabel(result!.mean,'bpm')}. {result!.coverage<.9?'La cobertura es parcial: la distribución solo describe el tiempo observado.':'La cobertura temporal es alta; esto no garantiza que el sensor sea exacto.'} Los huecos de más de 10 segundos no se rellenan.</p>
    </>}
    <h3>{result&&zones?'Tiempo en tus zonas · tramo seleccionado':'Tiempo en zonas de origen · sesión completa'}</h3>
    {dominant&&total>0&&<p className="hrExplanation">El rango con más tiempo observado es {dominant.label} ({dominant.range}): {hrTime(dominant.seconds)}, un {(100*dominant.seconds/total).toLocaleString('es-ES',{maximumFractionDigits:1})} % del tiempo clasificado. Esto describe dónde se concentró la respuesta cardíaca; no permite atribuir por sí solo un efecto concreto del entrenamiento.</p>}
    {rows&&total>0?<><div className="hrZoneBars">{rows.map((z,i)=><div key={z.label}><span><b>{z.label}</b><small>{z.range}</small></span><div className="hrBarTrack"><i style={{width:`${100*z.seconds/total}%`,background:colors[Math.min(i,6)]}}/></div><span>{hrTime(z.seconds)}<small>{(100*z.seconds/total).toFixed(1)} %</small></span></div>)}</div><p>{result&&zones?`${zones.label}. Tiempo clasificado: ${hrTime(total)}. Los límites inferiores son inclusivos; el límite superior solo lo es en Z5.`:`Distribución entregada por Intervals: ${hrTime(total)} clasificados. Conserva los límites originales y no se recalcula con tu configuración sin una curva temporal.`} Una zona describe un rango de FC; no identifica por sí sola un sistema energético ni demuestra adaptación.</p></>:<p>No hay distribución utilizable. Introducir una máxima no permite deducir tiempo en zonas a partir de la media.</p>}
    <section className="hrCompare"><h3>FC a potencia o velocidad parecida</h3><label>Buscar sesiones por<select value={mode} onChange={e=>{setMode(e.target.value as 'power'|'speed');setPeerId('');}}><option value="power">Potencia media medida</option><option value="speed">Velocidad media / ritmo</option></select></label><p>Mismo deporte y fuente, 180 días anteriores, ±10 % en {mode==='power'?'potencia media con dispositivo declarado':'velocidad media'}, ±20 % en duración y desnivel (margen mínimo de 100 m). Son filtros de comparación, no equivalencia fisiológica.</p>
      <select aria-label="Actividad para comparar FC" value={peerId} onChange={e=>setPeerId(e.target.value)}><option value="">{peers.length?`${peers.length} ${peers.length===1?'sesión parecida':'sesiones parecidas'} · selecciona una`:'Sin sesiones que cumplan estos criterios'}</option>{peers.map(p=><option key={p.session.id} value={p.session.id}>{p.session.physiological_date} · {p.session.summary?.name??p.session.activity_type} · {numberLabel(mode==='power'?p.value:p.value*3.6,mode==='power'?'W':'km/h')}</option>)}</select>
      {peer&&<><div className="hrStats"><div><small>Esta sesión · FC media</small><strong>{numberLabel(session.avg_heart_rate_bpm,'bpm')}</strong></div><div><small>{peer.session.physiological_date} · FC media</small><strong>{numberLabel(peer.hr,'bpm')}</strong></div><div><small>Diferencia entre medias</small><strong>{hrNumber(session.avg_heart_rate_bpm,25,250)!==null?`${(session.avg_heart_rate_bpm!-peer.hr).toFixed(1)} bpm`:'Sin dato'}</strong></div></div><p>Comparación de resúmenes: una media de FC distinta con trabajo medio parecido no demuestra mayor eficiencia. Las pausas, el perfil de esfuerzo, el terreno, el viento, el calor y el sensor pueden diferir. {peer.source?.device_name&&source?.device_name&&peer.source.device_name===source.device_name?'Coincide el nombre del dispositivo de origen; no confirma el mismo sensor de FC.':'No se ha confirmado continuidad de dispositivo.'}</p>
      {stream&&!peerStream&&canImport&&<button disabled={busy} onClick={()=>fetchStream(peer.session.id)}>Obtener curva de la sesión comparada</button>}
      {stream&&peerStream&&<><h4>FC dentro de bandas de trabajo externo comunes</h4><p>Se excluyen los primeros 10 minutos. Bandas de {mode==='power'?'25 W':'0,5 m/s'}, con al menos 3 minutos observados en cada sesión. Se usan los mismos intervalos temporales para FC y trabajo externo, sin corregir el retardo cardíaco.</p>{bands.length?<div className="hrTable"><table><thead><tr><th>{mode==='power'?'Potencia':'Velocidad'}</th><th>Esta sesión</th><th>Comparada</th><th>Diferencia</th></tr></thead><tbody>{bands.map(b=><tr key={b.low}><td>{mode==='power'?`${b.low}–<${b.high} W`:`${(b.low*3.6).toFixed(1)}–<${(b.high*3.6).toFixed(1)} km/h`}</td><td>{b.a.toFixed(1)} bpm<br/><small>{hrTime(b.aSeconds)}</small></td><td>{b.b.toFixed(1)} bpm<br/><small>{hrTime(b.bSeconds)}</small></td><td>{(b.a-b.b).toFixed(1)} bpm</td></tr>)}</tbody></table></div>:<p>No hay bandas con suficiente tiempo común para una comparación estable.</p>}<p>Es una asociación descriptiva. Los cambios rápidos de carga y el retardo de la FC pueden sesgarla; no se interpreta como mejora de forma física.</p></>}
      </>}
    </section>
    {status&&<p role="status">{status}</p>}
    <details><summary>Método, calidad y referencias</summary><p>Versión hr-analysis-v1. Curvas: muestras de origen, ponderadas por segundos entre puntos consecutivos (hasta 10 s). FC fuera de 25–250 bpm se considera no utilizable; esto solo detecta extremos, no todos los artefactos. Última muestra sin intervalo posterior excluida del cómputo de tiempo. La línea conserva huecos y se resume visualmente por grupos, manteniendo mínimos y máximos; los cálculos usan todos los puntos.</p><p>La FC depende tanto del trabajo externo como del contexto. No se diagnostican arritmias, fatiga, umbrales ni recuperación con este análisis. No se compara potencia estimada como si fuera medida. En trail, la velocidad media no controla la pendiente o la dificultad técnica.</p><p><a href="https://pubmed.ncbi.nlm.nih.gov/11153730/" target="_blank" rel="noreferrer">Tanaka et al.: estimación de FC máxima en adultos</a> · <a href="https://www.polar.com/us-en/guide/heart-rate-zones" target="_blank" rel="noreferrer">Convención de cinco zonas por % de máxima</a> · <a href="https://forum.intervals.icu/t/server-side-data-model-for-scripts/25781/1" target="_blank" rel="noreferrer">Definiciones y unidades de Intervals</a></p><p>Registro de origen: {session.source_record_id??'sin vínculo'} · configuración: {chosen?.updated_at??'referencia de origen / sin configuración personal'}.</p></details>
  </section>;
}
export function HeartRateChart({stream,zones,from,to}:{stream:HrStream;zones:number[];from:number;to:number}){
  const valid=stream.heartrate.filter((n):n is number=>n!==null),lo=Math.max(20,valid.reduce((a,b)=>Math.min(a,b),60)),hi=Math.min(260,valid.reduce((a,b)=>Math.max(a,b),180)),end=stream.time.at(-1)||1;
  const x=(t:number)=>45+t/end*700,y=(v:number)=>220-(v-lo)/(hi-lo)*190;
  const segments:string[]=[];let path='';let last=-1;
  // Bound SVG size while retaining extrema of each group and splitting at every missing sample/gap.
  const step=Math.max(1,Math.ceil(stream.time.length/1500));
  for(let i=0;i<stream.time.length;i+=step){const indices=Array.from({length:Math.min(step,stream.time.length-i)},(_,j)=>i+j);const hasGap=indices.some(k=>stream.heartrate[k]===null||(k>0&&stream.time[k]-stream.time[k-1]>10));const use=hasGap?indices:[indices[0],indices.reduce((a,b)=>stream.heartrate[a]!<stream.heartrate[b]!?a:b),indices.reduce((a,b)=>stream.heartrate[a]!>stream.heartrate[b]!?a:b),indices.at(-1)!].sort((a,b)=>a-b);for(const k of [...new Set(use)]){const v=stream.heartrate[k];if(v===null){if(path)segments.push(path);path='';last=-1;continue;}if(last>=0&&stream.time[k]-stream.time[last]>10&&hasGap){if(path)segments.push(path);path='';}path+=`${path?'L':'M'}${x(stream.time[k]).toFixed(1)},${y(v).toFixed(1)} `;last=k;}}
  if(path)segments.push(path);
  return <svg className="hrChart" viewBox="0 0 780 260" role="img" aria-label="Curva de frecuencia cardíaca en bpm y minutos desde el inicio"><rect x={x(from)} y="20" width={Math.max(0,x(to)-x(from))} height="205" fill="#edf3e8"/>{[lo,(lo+hi)/2,hi].map(v=><g key={v}><line x1="45" x2="745" y1={y(v)} y2={y(v)} stroke="#dee5da"/><text x="38" y={y(v)+4} textAnchor="end">{Math.round(v)}</text></g>)}{zones.filter(v=>v>=lo&&v<=hi).map(v=><line key={v} x1="45" x2="745" y1={y(v)} y2={y(v)} stroke="#b5c4ac" strokeDasharray="3 5"/>)}{segments.map((d,i)=><path key={i} d={d} fill="none" stroke="#aa554b" strokeWidth="1.5"/>)}{[0,.25,.5,.75,1].map(f=><text key={f} x={x(f*end)} y="245" textAnchor="middle">{Math.round(f*end/60)} min</text>)}</svg>;
}
