import {useEffect,useMemo,useRef,useState} from 'react';
import {useSubject} from '../subjects/SubjectProvider';
import type {TrainingSession} from '../repositories/activities';
import {getClimbAnalyses,importClimbAnalysis} from '../repositories/cycling-climbs';
import {getHrSources} from '../repositories/heart-rate';
import {climbGroups,matchClimbs,cyclingSports,type ClimbAnalysis,type ClimbRow} from '../health/cycling-climbs';
import {sportLabel} from '../health/activities';
import './cycling-climbs.css';
const num=(v:number|null,unit='')=>v===null?'—':`${v.toLocaleString('es-ES',{maximumFractionDigits:1})}${unit}`;
export default function CyclingClimbs({sessions,onOpen}:{sessions:TrainingSession[];onOpen:(id:string)=>void}){
  const {scope}=useSubject();return scope?<Climbs key={scope.subjectId} subjectId={scope.subjectId} userId={scope.dataUserId} editable={['admin','owner','editor'].includes(scope.permission)} sessions={sessions} onOpen={onOpen}/>:null;
}
function Climbs({subjectId,userId,editable,sessions,onOpen}:{subjectId:string;userId:string;editable:boolean;sessions:TrainingSession[];onOpen:(id:string)=>void}){
  const [analyses,setAnalyses]=useState(new Map<string,ClimbAnalysis>()),[sources,setSources]=useState(new Map<string,Record<string,unknown>>());
  const [status,setStatus]=useState('Cargando análisis…'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
  const [sport,setSport]=useState('Ride'),[bin,setBin]=useState<number|null>(null),[mode,setMode]=useState<'hr'|'speed'>('hr'),[showFlagged,setShowFlagged]=useState(false),[limit,setLimit]=useState(30);
  const cancelled=useRef(false),mounted=useRef(true);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;cancelled.current=true;};},[]);
  useEffect(()=>{let active=true;setLoading(true);Promise.all([getClimbAnalyses(subjectId),getHrSources(userId)]).then(([a,s])=>{if(active){setAnalyses(a);setSources(s);setStatus('');setLoading(false);}}).catch(()=>{if(active){setStatus('No se pudo cargar el análisis. Pulsa actualizar para reintentar.');setLoading(false);}});return()=>{active=false;};},[subjectId,userId,revision]);
  const cycling=sessions.filter(s=>cyclingSports.includes(s.activity_type));
  const pending=cycling.filter(s=>s.provider==='intervals_icu'&&!analyses.has(s.id));
  const importAll=async()=>{cancelled.current=false;setBusy(true);let done=0,failed=0;for(const s of pending){if(cancelled.current)break;setStatus(`Importando ${done+failed+1}/${pending.length} actividades…`);try{const a=await importClimbAnalysis(subjectId,s.id);if(!mounted.current)break;setAnalyses(old=>new Map(old).set(s.id,a));done++;}catch(e){failed++;if(!mounted.current)break;setStatus(e instanceof Error?e.message:'Error de importación');break;}}if(mounted.current){setBusy(false);setStatus(`${done} importadas${failed?` · ${failed} error; vuelve a intentar para continuar`:''}${cancelled.current?' · detenido':''}.`);}};
  const rows=useMemo(()=>cycling.flatMap(s=>{
    const a=analyses.get(s.id),source=s.source_record_id?sources.get(s.source_record_id):null;
    const validSource=source?.external_id===s.external_session_id;
    return (a?.segments??[]).map(r=>({...r,sessionId:s.id,date:s.physiological_date,sport:s.activity_type,provider:s.provider,device:validSource&&typeof source?.device_name==='string'?source.device_name:null,method:a?.method??'unknown',flagged:Boolean(a?.sourceFlagged)||!validSource}));
  }),[sessions,analyses,sources]);
  const selectedSport=rows.filter(r=>r.sport===sport),flagged=selectedSport.filter(r=>r.flagged);
  const available=selectedSport.filter(r=>showFlagged||!r.flagged),groups=climbGroups(available);
  const selectedBin=bin!==null&&groups.some(g=>g.bin===bin)?bin:[...groups].sort((a,b)=>b.segments-a.segments)[0]?.bin;
  const selected=available.filter(r=>r.bin===selectedBin),matched=matchClimbs(selected,mode);
  const unit=mode==='hr'?' bpm':' km/h',value=(r:ClimbRow)=>mode==='hr'?r.hr:r.speed;
  const plotted=selected.filter(r=>value(r)!==null).sort((a,b)=>a.date.localeCompare(b.date));
  const W=900,H=280,L=58,R=20,T=20,B=40;
  const first=Date.parse(plotted[0]?.date??'2026-01-01'),last=Date.parse(plotted.at(-1)?.date??'2026-01-02');
  const values=plotted.map(r=>value(r)!),min=values.length?Math.min(...values):0,max=values.length?Math.max(...values):1,pad=Math.max((max-min)*.12,1);
  const x=(r:ClimbRow)=>L+(Date.parse(r.date)-first)/Math.max(86400000,last-first)*(W-L-R),y=(r:ClimbRow)=>T+(max+pad-value(r)!)/(max-min+pad*2)*(H-T-B);
  const download=()=>{const lines=['date,session_id,start_seconds,end_seconds,grade_percent,speed_kmh,hr_bpm,hr_coverage,source_flagged',...rows.map(r=>[r.date,r.sessionId,r.start,r.end,r.grade,r.speed,r.hr??'',r.hrCoverage,r.flagged].join(','))];const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='healthos-subidas-5min.csv';a.click();URL.revokeObjectURL(url);};
  return <section className="climbPanel">
    <header><div><div className="eyebrow">CICLISMO · EVOLUCIÓN EN SUBIDA</div><h2>La misma pendiente, otra respuesta</h2><p>Bloques de cinco minutos en subidas continuas. Velocidad y FC observadas, con comparaciones entre salidas.</p></div><button disabled={busy||loading} onClick={()=>setRevision(r=>r+1)}>Actualizar análisis</button></header>
    <div className="climbStats"><div><strong>{cycling.length}</strong><span>actividades de ciclismo exterior</span></div><div><strong>{cycling.filter(s=>analyses.has(s.id)).length}</strong><span>actividades procesadas</span></div><div><strong>{rows.length}</strong><span>bloques de cinco minutos</span></div><div><strong>{num(rows.length?Math.max(...rows.map(r=>r.grade)):null,'%')}</strong><span>pendiente media máxima de un bloque</span></div></div>
    {pending.length>0&&<p>{pending.length} actividades pendientes de importar. {editable&&<button disabled={busy||loading} onClick={importAll}>Importar pendientes</button>}</p>}{busy&&<button onClick={()=>{cancelled.current=true;}}>Detener después de esta actividad</button>}{status&&<p role="status">{status}</p>}
    <div className="climbControls"><label>Modalidad<select value={sport} onChange={e=>{setSport(e.target.value);setBin(null);setLimit(30);}}>{cyclingSports.map(s=><option key={s} value={s}>{s==='GravelRide'?'Gravel':sportLabel(s)}</option>)}</select></label><label>Qué comparar<select value={mode} onChange={e=>setMode(e.target.value as 'hr'|'speed')}><option value="hr">FC a velocidad parecida</option><option value="speed">Velocidad a FC parecida</option></select></label><button disabled={!rows.length} onClick={download}>Exportar bloques CSV</button></div>
    {flagged.length>0&&<div className="climbQuality"><strong>{new Set(flagged.map(r=>r.sessionId)).size} salidas con datos marcados para ignorar en origen</strong><p>Sus {flagged.length} bloques quedan fuera de la comparación. La marca puede corresponder a FC o velocidad; no la anulamos al recalcular.</p><label><input type="checkbox" checked={showFlagged} onChange={e=>setShowFlagged(e.target.checked)}/> Mostrar también esos bloques para explorarlos</label></div>}
    <h3>Elige la pendiente media</h3><div className="climbBins">{groups.map(g=><button key={g.bin} aria-pressed={selectedBin===g.bin} onClick={()=>{setBin(g.bin);setLimit(30);}}><strong>{g.bin}–{g.bin+1}%</strong><small>{g.rides} salidas · {g.segments} bloques</small></button>)}</div>
    {!loading&&!groups.length&&<p>No hay bloques disponibles con estos criterios. Puede faltar una subida continua de cinco minutos o haber datos excluidos por origen.</p>}
    {selected.length>0&&<><div className="climbReading"><h3>{matched.delta===null?'Aún no hay suficientes pares comparables':`${mode==='hr'?'FC':'Velocidad'} ${num(Math.abs(matched.delta),unit)} ${matched.delta===0?'sin diferencia':matched.delta<0?'menor':'mayor'} en la comparación`}</h3><p>{matched.pairs.length} pares de salidas distintas. {matched.eligible?'Es la mediana de las diferencias entre pares; un patrón compatible con cambios de respuesta, no una demostración de adaptación.':'Se necesitan al menos tres pares y tres fechas diferentes en cada mitad del historial seleccionado.'}</p><p>{mode==='hr'?'Velocidad dentro de ±5 %.':'FC dentro de ±3 bpm.'} Pendiente dentro de ±0,25 puntos; misma modalidad, proveedor, dispositivo declarado y método de altitud. Separación mínima de 28 días. Cada salida se utiliza una sola vez.</p></div>
      <div className="climbPlot"><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label={`Historial de ${mode==='hr'?'FC':'velocidad'} en bloques al ${selectedBin}–${selectedBin!+1}%`}>{[0,.25,.5,.75,1].map(f=>{const v=min-pad+f*(max-min+pad*2),yy=T+(1-f)*(H-T-B);return <g key={f}><line x1={L} x2={W-R} y1={yy} y2={yy} stroke="#e1e7dc"/><text x={L-8} y={yy+4} textAnchor="end">{num(v)}</text></g>;})}{matched.pairs.map((p,i)=><line key={i} x1={x(p.before)} x2={x(p.after)} y1={y(p.before)} y2={y(p.after)} stroke="#b59767" strokeWidth="1.5" opacity=".7"/>)}{plotted.map(r=><circle key={`${r.sessionId}-${r.start}`} cx={x(r)} cy={y(r)} r="3.5" fill={r.flagged?'#aab0aa':'#386d53'}><title>{r.date} · {num(r.grade,'%')} · {num(r.speed,' km/h')} · {num(r.hr,' bpm')}</title></circle>)}{[0,.5,1].map(f=><text key={f} x={L+f*(W-L-R)} y={H-10} textAnchor={f===0?"start":f===1?"end":"middle"}>{new Date(first+f*(last-first)).toISOString().slice(0,10)}</text>)}</svg></div><p className="climbNote">Cada punto es un bloque de cinco minutos. Eje vertical: {mode==='hr'?'FC media (bpm)':'velocidad media (km/h)'}. Las líneas unen pares comparables, no una tendencia ajustada. El resto de puntos aporta contexto.</p>
      <details><summary>Ver los pares utilizados ({matched.pairs.length})</summary><div className="climbTable"><table><thead><tr><th>Antes → después</th><th>Pendiente</th><th>Velocidad</th><th>FC</th><th>Diferencia</th></tr></thead><tbody>{matched.pairs.map(p=><tr key={p.after.sessionId}><td>{p.before.date} → {p.after.date}</td><td>{num(p.before.grade)} → {num(p.after.grade,'%')}</td><td>{num(p.before.speed)} → {num(p.after.speed,' km/h')}</td><td>{num(p.before.hr)} → {num(p.after.hr,' bpm')}</td><td>{num(p.delta,unit)}</td></tr>)}</tbody></table></div></details>
    </>}
    {groups.length>0&&<details><summary>Resumen por pendiente · todas las bandas disponibles</summary><div className="climbTable"><table><thead><tr><th>Pendiente</th><th>Salidas / bloques</th><th>Velocidad</th><th>FC</th></tr></thead><tbody>{groups.map(g=><tr key={g.bin}><td>{g.bin}–{g.bin+1}%</td><td>{g.rides} / {g.segments}</td><td>{num(g.speed,' km/h')}</td><td>{num(g.hr,' bpm')}</td></tr>)}</tbody></table></div><p className="climbNote">Primero se promedian los bloques de cada salida; después se muestra la mediana entre salidas. Así una salida larga no domina el resumen.</p></details>}
    {selected.length>0&&<details><summary>Inspeccionar los {selected.length} bloques de esta pendiente</summary><div className="climbTable"><table><thead><tr><th>Fecha</th><th>Desde el inicio</th><th>Pendiente media / rango</th><th>Velocidad</th><th>FC / cobertura</th><th>Origen</th></tr></thead><tbody>{[...selected].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,limit).map(r=><tr key={`${r.sessionId}-${r.start}`}><td><button onClick={()=>onOpen(r.sessionId)}>{r.date}</button></td><td>{Math.floor(r.start/60)}–{Math.floor(r.end/60)} min</td><td>{num(r.grade,'%')} / {num(r.gradeMin)}–{num(r.gradeMax,'%')}</td><td>{num(r.speed,' km/h')}</td><td>{num(r.hr,' bpm')} / {num(r.hrCoverage*100,'%')}</td><td>{r.flagged?'Marcado para ignorar':'Sin marca de exclusión'}</td></tr>)}</tbody></table></div>{selected.length>limit&&<button onClick={()=>setLimit(n=>n+30)}>Mostrar 30 más</button>}</details>}
    <details><summary>Método y límites de la comparación</summary><p>Pendiente estimada mediante cambio de altitud por distancia recorrida en una ventana cercana a 100 m (75–200 m). Se prefiere la altitud corregida de Intervals. Los bloques consecutivos, sin solapamiento, duran exactamente 300 s dentro de una subida estimada ≥1 %. Se reinicia al parar, bajar o encontrar huecos mayores de 10 s. Se descartan velocidades fuera de 3,6–90 km/h y pendientes locales superiores al 30 % como filtro de calidad.</p><p>La pendiente media se pondera por distancia; la FC por tiempo, con al menos 90 % de cobertura. La velocidad se calcula con distancia/tiempo. Los restos menores de cinco minutos no se incluyen. Para emparejar se exige además un rango de pendiente local de como máximo tres puntos porcentuales. La comparación divide las fechas válidas en dos mitades y empareja cronológicamente sin reutilizar salidas; no busca sólo los mejores resultados.</p><p>Igual pendiente y velocidad no equivalen al mismo trabajo mecánico. Viento, masa, bicicleta, asfalto, fatiga, temperatura y respuesta del sensor pueden cambiar. Tampoco se ha confirmado que los tramos sean el mismo lugar. Una FC menor puede tener varias explicaciones; estas comparaciones no certifican una mejora fisiológica.</p><a href="https://forum.intervals.icu/t/server-side-data-model-for-scripts/25781/29" target="_blank" rel="noreferrer">Origen y limitaciones de la pendiente en Intervals</a></details>
  </section>;
}

