import {useEffect,useState} from 'react';
import {useSubject} from '../subjects/SubjectProvider';
import {getHrSettings,saveHrSettings} from '../repositories/heart-rate';
import {resolveZones,settingsError,type HrSettings} from '../health/heart-rate';
import {sportLabel} from '../health/activities';
import './heart-rate.css';
export default function HeartRateSettings({sport='all',onChange}:{sport?:string;onChange?:()=>void}){
  const {scope}=useSubject();return scope?<Settings key={`${scope.subjectId}:${sport}`} subjectId={scope.subjectId} sport={sport} editable={['admin','owner','editor'].includes(scope.permission)} name={scope.displayName??'Perfil'} onChange={onChange}/>:null;
}
export function Settings({subjectId,sport,editable,name,onChange}:{subjectId:string;sport:string;editable:boolean;name:string;onChange?:()=>void}){
  const blank:HrSettings={subject_id:subjectId,sport,method:'max',max_hr:null,rest_hr:null,date_of_birth:null,custom_edges:null};
  const [form,setForm]=useState(blank),[custom,setCustom]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  useEffect(()=>{let active=true;getHrSettings(subjectId).then(rows=>{if(!active)return;const row=rows.find(r=>r.sport===sport);if(row){setForm(row);setCustom(row.custom_edges?.join(', ')??'');}setLoading(false);}).catch(()=>{if(active){setStatus('No se pudo cargar la configuración. Vuelve a abrir la vista.');setLoading(true);}});return()=>{active=false;};},[subjectId,sport]);
  const input={...form,custom_edges:custom.trim()?custom.split(/[,;\s]+/).map(Number):null};const preview=resolveZones(input,null,new Date().toISOString().slice(0,10));
  const save=async()=>{const problem=settingsError(input);if(problem){setStatus(problem);return;}setSaving(true);try{const row=await saveHrSettings(input);setForm(row);setStatus('Configuración guardada.');onChange?.();window.dispatchEvent(new CustomEvent('healthos-hr-settings',{detail:subjectId}));}catch{setStatus('No se pudo guardar. Los cambios no se han aplicado.');}finally{setSaving(false);}};
  return <details className="hrSettings"><summary>Configurar zonas de FC · {sport==='all'?'Todos los deportes':sportLabel(sport)}</summary><h3>FC de {name}</h3><p>La configuración de un deporte tiene prioridad sobre la general. Se aplica como relectura actual del historial; no representa necesariamente los límites que usabas entonces.</p><fieldset disabled={!editable||loading||saving}><div className="hrSettingsGrid"><label>Método<select value={form.method} onChange={e=>setForm({...form,method:e.target.value as HrSettings['method']})}><option value="max">% de FC máxima · 5 zonas</option><option value="reserve">Reserva de FC · 5 bandas</option><option value="custom">Límites manuales · 5 zonas</option></select></label><label>FC máxima personal (bpm)<input type="number" min="60" max="240" value={form.max_hr??''} onChange={e=>setForm({...form,max_hr:e.target.value?Number(e.target.value):null})}/></label><label>FC de reposo personal (bpm)<input type="number" min="25" max="120" value={form.rest_hr??''} onChange={e=>setForm({...form,rest_hr:e.target.value?Number(e.target.value):null})}/></label><label>Fecha de nacimiento · para estimación<input type="date" value={form.date_of_birth??''} onChange={e=>setForm({...form,date_of_birth:e.target.value||null})}/></label></div>{form.method==='custom'&&<label>Inicio de Z1, Z2, Z3, Z4, Z5 y fin de Z5 (bpm)<input value={custom} placeholder="90, 110, 130, 150, 170, 190" onChange={e=>setCustom(e.target.value)}/></label>}<button onClick={save}>{saving?'Guardando…':'Guardar zonas'}</button></fieldset>{preview&&<p>Vista previa: {preview.edges.join(' · ')} bpm. {preview.label}.</p>}<p>Sin FC máxima personal: máxima configurada en la actividad de origen; si falta, 208 − 0,7 × edad para adultos de 18–100 años. Sin ninguna de esas referencias, no se inventan límites. La FC máxima registrada en una salida no se convierte automáticamente en tu máxima personal.</p><p>Las bandas 50–60–70–80–90–100 % son una convención. En reserva se aplica FC reposo + porcentaje × (FC máxima − FC reposo). No equivalen a umbrales de lactato ni a una prescripción individual.</p>{!editable&&<p>Tu acceso a este perfil es de lectura.</p>}{status&&<p role="status">{status}</p>}</details>;
}
