import {useState} from 'react';
import type {TrainingSession} from '../repositories/activities';
import {cardiacComparison,externalWork,type HrPeer} from '../health/hr-comparison';
import {hrNumber,hrTime,matchedEffort} from '../health/heart-rate';
const currentColor='#386b55',otherColor='#b08035';
const f=(v:number)=>v.toLocaleString('es-ES',{maximumFractionDigits:1});
export function HrSessionScatter({session,source,peers,selectedId,onSelect,mode}:{session:TrainingSession;source:Record<string,unknown>|null;peers:HrPeer[];selectedId:string;onSelect:(id:string)=>void;mode:'power'|'speed'}){
  const work=externalWork(source??undefined,mode),hr=hrNumber(session.avg_heart_rate_bpm,25,250),factor=mode==='power'?1:3.6;
  if(work===null||hr===null||!peers.length)return <p>No hay suficientes resúmenes comparables para dibujar la gráfica.</p>;
  const points=[{id:session.id,x:work*factor,y:hr,date:session.physiological_date},...peers.map(p=>({id:p.session.id,x:p.value*factor,y:p.hr,date:p.session.physiological_date}))];
  const xMin=Math.min(...points.map(p=>p.x)),xMax=Math.max(...points.map(p=>p.x)),yMin=Math.min(...points.map(p=>p.y)),yMax=Math.max(...points.map(p=>p.y));
  const xPad=Math.max(mode==='power'?5:1,(xMax-xMin)*.15),yPad=Math.max(5,(yMax-yMin)*.15);
  const x=(v:number)=>55+(v-xMin+xPad)/(xMax-xMin+2*xPad)*570,y=(v:number)=>235-(v-yMin+yPad)/(yMax-yMin+2*yPad)*195;
  return <div className="hrComparisonVisual"><h4>Tu historial: trabajo externo y respuesta cardíaca</h4><p>Horizontal: {mode==='power'?'potencia media declarada por dispositivo':'velocidad media'}. Vertical: FC media. Más abajo significa menos pulsaciones registradas, no automáticamente mejor rendimiento.</p><svg viewBox="0 0 690 295" role="group" aria-label="Sesiones comparables por trabajo externo y frecuencia cardíaca"><text x="12" y="18">FC · bpm</text>{[0,.5,1].map(t=>{const xv=xMin-xPad+t*(xMax-xMin+2*xPad),yv=yMin-yPad+t*(yMax-yMin+2*yPad);return <g key={t}><line x1="55" x2="625" y1={y(yv)} y2={y(yv)} stroke="#e0e6da"/><text x="48" y={y(yv)+4} textAnchor="end">{f(yv)}</text><text x={x(xv)} y="255" textAnchor="middle">{f(xv)}</text></g>;})}{points.map(p=><g key={p.id} role={p.id===session.id?'img':'button'} tabIndex={p.id===session.id?undefined:0} aria-label={`${p.id===session.id?'Esta sesión':p.date}: ${f(p.x)} ${mode==='power'?'W':'km/h'}, ${f(p.y)} bpm`} onClick={()=>{if(p.id!==session.id)onSelect(p.id);}} onKeyDown={e=>{if(p.id!==session.id&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onSelect(p.id);}}}><title>{p.date}: {f(p.x)} {mode==='power'?'W':'km/h'} · {f(p.y)} bpm</title><circle cx={x(p.x)} cy={y(p.y)} r={p.id===session.id||p.id===selectedId?7:4.5} fill={p.id===session.id?currentColor:p.id===selectedId?otherColor:'#a6b7a4'} stroke="white" strokeWidth="2"/>{(p.id===session.id||p.id===selectedId)&&<text x={x(p.x)} y={y(p.y)-12} textAnchor="middle">{p.id===session.id?'Esta sesión':'Comparada'}</text>}</g>)}<text x="345" y="286" textAnchor="middle">{mode==='power'?'Potencia media (W)':'Velocidad media (km/h)'}</text></svg><div className="hrGraphLegend"><span style={{color:currentColor}}>● Esta sesión</span><span style={{color:otherColor}}>● Sesión seleccionada</span><span>● {peers.length} anteriores que cumplen los filtros</span></div></div>;
}
export function HrComparisonExplanation({session,source,peer,mode}:{session:TrainingSession;source:Record<string,unknown>|null;peer:HrPeer;mode:'power'|'speed'}){
  const c=cardiacComparison(session,source,peer,mode);
  return <div className="hrComparisonReading"><span className="eyebrow">QUÉ CAMBIÓ</span><h4>{c.direction}</h4><p>{c.work}</p><p>{c.interpretation}</p><div className="hrTable"><table><thead><tr><th>Contexto de la comparación</th><th>Esta sesión</th><th>{peer.session.physiological_date}</th></tr></thead><tbody>{c.rows.map(r=><tr key={r.label}><td>{r.label}</td><td>{r.a===null?'Sin dato':`${f(r.a/r.divisor)} ${r.unit}`}</td><td>{r.b===null?'Sin dato':`${f(r.b/r.divisor)} ${r.unit}`}</td></tr>)}</tbody></table></div><p>{c.sameRoute?'Coincide la referencia de ruta en origen; no garantiza las mismas condiciones.':'No se ha confirmado la misma ruta.'} {c.sameDevice?'Coincide el nombre del dispositivo, pero no confirma el mismo sensor de FC.':'No se ha confirmado el mismo dispositivo.'}</p><p>{mode==='speed'?'La velocidad no mide directamente el trabajo: en bicicleta influyen viento, pendiente y rodar a rueda; en trail, pendiente y dificultad técnica.':'Una potencia parecida controla mejor el trabajo externo, pero la distribución del esfuerzo y el contexto pueden ser diferentes.'} Para valorar una posible mejora necesitamos que el patrón se repita en sesiones comparables, con señal fiable.</p></div>;
}
export function HrBandChart({bands,mode}:{bands:ReturnType<typeof matchedEffort>;mode:'power'|'speed'}){
  const [selected,setSelected]=useState<number|null>(null);if(!bands.length)return null;
  const active=bands.find(b=>b.low===selected)??bands.reduce((a,b)=>Math.min(a.aSeconds,a.bSeconds)>=Math.min(b.aSeconds,b.bSeconds)?a:b);
  const values=bands.flatMap(b=>[b.a,b.b]),low=Math.min(...values)-5,high=Math.max(...values)+5;
  const x=(i:number)=>bands.length===1?345:60+i/(bands.length-1)*570,y=(v:number)=>220-(v-low)/(high-low)*170;
  return <div className="hrComparisonVisual"><h4>Dos respuestas cardíacas dentro de la misma banda</h4><svg viewBox="0 0 690 285" role="group" aria-label="Comparación de frecuencia cardíaca en bandas comunes"><text x="12" y="18">FC · bpm</text>{[low,(low+high)/2,high].map(v=><g key={v}><line x1="55" x2="640" y1={y(v)} y2={y(v)} stroke="#e0e6da"/><text x="48" y={y(v)+4} textAnchor="end">{f(v)}</text></g>)}{bands.map((b,i)=><g key={b.low} role="button" tabIndex={0} aria-label={`Banda ${f(b.low)} a ${f(b.high)}, diferencia ${f(b.a-b.b)} bpm`} onClick={()=>setSelected(b.low)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(b.low);}}}><line x1={x(i)} x2={x(i)} y1={y(b.a)} y2={y(b.b)} stroke="#c3c9bb" strokeWidth={b.low===active.low?4:2}/><circle cx={x(i)} cy={y(b.a)} r="6" fill={currentColor}/><circle cx={x(i)} cy={y(b.b)} r="6" fill={otherColor}/><text x={x(i)} y="247" textAnchor="middle">{f((b.low+b.high)/2*(mode==='power'?1:3.6))}</text></g>)}<text x="345" y="278" textAnchor="middle">Centro de banda · {mode==='power'?'W':'km/h'}</text></svg><div className="hrGraphLegend"><span style={{color:currentColor}}>● Esta sesión</span><span style={{color:otherColor}}>● Comparada</span></div><p className="hrExplanation">En {f(active.low*(mode==='power'?1:3.6))}–&lt;{f(active.high*(mode==='power'?1:3.6))} {mode==='power'?'W':'km/h'}: {f(active.a)} frente a {f(active.b)} bpm, {f(Math.abs(active.a-active.b))} bpm {active.a<active.b?'menos':'más'} en esta sesión. Se observaron {hrTime(active.aSeconds)} y {hrTime(active.bSeconds)}, respectivamente. La banda agrupa trabajo parecido, no condiciones idénticas.</p></div>;
}
