import Interpretation from './Interpretation';
import { questionNarrative } from '../health/interpretation';
import { formatMonitoring, MONITORING_METRICS } from '../health/monitoring-metrics';
import { formatClock, QUESTION_STATES, type QuestionMemory, type WeeklyLearning, type WeeklyQuestion } from '../health/weekly-learning';
import './weekly-learning.css';
export const contextLabel = (type: string) => ({ travel: 'Viaje', illness: 'Enfermedad', late_dinner: 'Cena tardía', alcohol: 'Alcohol', medication: 'Medicación', routine_change: 'Cambio de rutina', sauna: 'Sauna', stress: 'Estrés' }[type] ?? type.replaceAll('_', ' '));
const dateLabel = (date: string) => new Date(`${date}T12:00:00Z`).toLocaleDateString('es-ES', { day: 'numeric', month: 'short' });
const signalLabel = (key: string) => MONITORING_METRICS.find(m => m.key === key)?.label ?? key;
const deltaLabel = (key: string, delta: number) => delta === 0 ? 'sin diferencia en la mediana' : `${key === 'sleep_duration' && Math.abs(delta) < 60 ? `${Math.round(Math.abs(delta))} min` : formatMonitoring(key, Math.abs(delta))} ${delta > 0 ? 'más' : 'menos'}`;
export default function WeeklyLearningPanel({ report, memories, following, onOpenTrend, onAddContext, onFollow }: {
  report: WeeklyLearning; memories: QuestionMemory[]; following: string[]; onOpenTrend?: (key: string) => void;
  onAddContext?: (date: string) => void; onFollow?: (question: WeeklyQuestion, following: boolean) => void;
}) {
  const rhythm = report.rhythm;
  const repeated = report.questions.filter(q => q.state === 'repeated');
  return <div className="weeklyLearning">
    <section className="weeklyLead"><div className="eyebrow">REVISIÓN SEMANAL · SUEÑO Y RECUPERACIÓN</div><h2>Qué distingue tus días</h2><p>{dateLabel(report.start)} – {dateLabel(report.end)} · Semana completa, de lunes a domingo.</p><div className="weeklyLeadStats"><span><b>{rhythm.recent.count}/7</b> noches con horario comparable</span><span><b>{repeated.length}</b> {repeated.length === 1 ? 'pregunta con una diferencia que reaparece' : 'preguntas con una diferencia que reaparece'}</span><span><b>{report.checkIns.length}/7</b> días con check-in</span></div></section>

    <section aria-label="Qué cambió"><h2>Qué cambió esta semana</h2><div className="weeklyChangeGrid">{report.changes.map(change => <article className="card" key={change.key}><div className="eyebrow">{change.label}</div><strong>{change.recentMedian === null ? 'Sin registros esta semana' : formatMonitoring(change.key, change.recentMedian)}</strong><p>{change.delta === null ? 'Todavía falta una comparación suficiente.' : `${deltaLabel(change.key, change.delta)} frente a las cuatro semanas anteriores.`}</p><small>{change.recent.length}/7 días esta semana · {change.prior.length}/28 anteriores.</small>{onOpenTrend && <button onClick={() => onOpenTrend(change.key)}>Explorar fechas →</button>}</article>)}</div>{!report.changes.length && <p>No hay señales diarias suficientes en esta ventana. Puedes explorar otra semana.</p>}</section>

    <section className="card weeklyRhythm" aria-label="Ritmo de sueño"><div className="eyebrow">DURACIÓN Y HORARIOS SON PREGUNTAS DISTINTAS</div><h2>Tu ritmo de sueño</h2>
      {rhythm.recent.bedtime ? <><div className="weeklyRhythmNumbers"><div><small>Inicio habitual del intervalo de sueño</small><strong>{formatClock(rhythm.recent.bedtime.minute)}</strong><span>Variación típica: {Math.round(rhythm.recent.bedtime.deviation)} min</span></div><div><small>Final habitual</small><strong>{formatClock(rhythm.recent.wake!.minute)}</strong><span>{rhythm.timezone}</span></div></div><p>{rhythm.bedtimeShift === null ? 'Faltan cinco noches comparables de la semana anterior para describir un cambio de horario.' : rhythm.bedtimeShift === 0 ? 'El inicio habitual coincide con el de la semana anterior.' : `El inicio habitual se ha desplazado ${Math.round(Math.abs(rhythm.bedtimeShift))} min ${rhythm.bedtimeShift > 0 ? 'más tarde' : 'más temprano'} respecto a la semana anterior.`}</p></> : <p>Se necesitan cinco noches con horarios y zona horaria comparables para resumir la regularidad. Las noches disponibles aparecen debajo.</p>}
      <div className="weeklyNights">{rhythm.recent.rows.map(night => <div key={night.date}><time>{dateLabel(night.date)}</time><span>{formatClock(night.bed)} → {formatClock(night.wake)}</span><strong>{formatMonitoring('sleep_duration', night.duration)}</strong>{onAddContext && <button aria-label={`Añadir contexto del ${night.date}`} onClick={() => onAddContext(night.date)}>＋ Contexto</button>}</div>)}</div>
      {rhythm.weekend.sleepDifference !== null && <div className="weeklyAside"><h3>¿Se distingue el fin de semana?</h3><p>En las últimas cuatro semanas, el sueño atribuido al sábado o domingo {rhythm.weekend.sleepDifference === 0 ? 'tiene la misma mediana de duración que el de lunes a viernes' : `dura ${deltaLabel('sleep_duration', rhythm.weekend.sleepDifference)} que el de lunes a viernes`}. {rhythm.weekend.wakeShift === 0 ? 'El final habitual coincide en ambos grupos.' : `El final habitual está ${Math.round(Math.abs(rhythm.weekend.wakeShift!))} min ${rhythm.weekend.wakeShift! > 0 ? 'más tarde' : 'más temprano'}.`}</p><small>{rhythm.weekend.weekendCount} noches de fin de semana y {rhythm.weekend.weekdayCount} entre semana. Se agrupan por fecha de despertar; no presupone tu horario laboral.</small></div>}
      <details><summary>Cómo leemos los horarios</summary><p>Usamos el intervalo más largo de cada día, de la misma fuente que el resumen de duración. Las siestas y duplicados no añaden noches. Los horarios se leen en la zona registrada; un cambio de zona o fuente interrumpe la comparación. La mediana circular evita interpretar 23:55 y 00:05 como horarios alejados. La variación típica es la mediana de las distancias al horario habitual. El intervalo registrado puede incluir tiempo despierto; la duración procede del resumen de sueño.</p></details>
    </section>

    <section aria-label="Preguntas que seguimos"><h2>Qué se repite y qué sigue abierto</h2><p className="muted">Cada pregunta conserva su referencia inicial. Revisarla otra semana no cuenta como una confirmación nueva. Las preguntas que sigues aparecen primero.</p>
      {[...report.questions].sort((a, b) => Number(following.includes(b.id)) - Number(following.includes(a.id))).map(q => {
        const last = q.blocks.filter(b => b.delta !== null).at(-1);
        const previous = memories.filter(m => m.questionId === q.id && m.weekEnd < report.end).sort((a, b) => b.weekEnd.localeCompare(a.weekEnd) || b.recordedAt.localeCompare(a.recordedAt))[0];
        const history = memories.filter(m => m.questionId === q.id && m.weekEnd <= report.end).sort((a, b) => b.weekEnd.localeCompare(a.weekEnd) || b.recordedAt.localeCompare(a.recordedAt)).slice(0, 8);
        return <article className="card weeklyQuestion" key={q.id}><div className="weeklyQuestionHeader"><span className={`weeklyState ${q.state}`}>{QUESTION_STATES[q.state]}</span>{onFollow && <button aria-pressed={following.includes(q.id)} onClick={() => onFollow(q, !following.includes(q.id))}>{following.includes(q.id) ? 'En seguimiento ✓' : 'Seguir esta pregunta'}</button>}</div><h3>{q.title}</h3><Interpretation narrative={questionNarrative(q)}/>
          {previous && previous.state !== q.state && <p className="weeklyRevision">En la revisión del {dateLabel(previous.weekEnd)}: «{QUESTION_STATES[previous.state]}». Ahora: «{QUESTION_STATES[q.state]}».</p>}
          <details><summary>Resultados y referencia de la comparación</summary>
          {!q.reference ? <p>{q.calibrationCount}/20 días disponibles para fijar la referencia en un primer periodo de 28 días. Aún no comparamos grupos.</p> : <>
            <p>Referencia fijada con {dateLabel(q.reference.start)} – {dateLabel(q.reference.end)}: <b>{formatMonitoring(q.x, q.reference.threshold)}</b>. {q.id === 'short-nights-hrv' ? 'Comparamos dos noches consecutivas por encima de tu referencia de duración con dos por debajo o igual, y la HRV atribuida al día siguiente. Esa referencia no define cuánto deberías dormir.' : q.id === 'steps-next-sleep' ? 'Los pasos de cada día se conectan con el sueño atribuido al siguiente.' : 'Sueño y pulso se emparejan por fecha fisiológica; no establece qué ocurrió primero.'}</p>
            {last ? <p className="weeklyAnswer"><b>{signalLabel(q.y)}: {deltaLabel(q.y, last.delta!)}</b> {q.id === 'steps-next-sleep' ? 'después de los días con más pasos que tu referencia, frente a los demás' : q.id === 'sleep-pulse' ? 'en las noches más largas que tu referencia, frente a las demás' : 'tras dos noches por encima de tu referencia de duración, frente a dos por debajo o igual'} · {last.matches.length} pares de días entre {dateLabel(last.start)} y {dateLabel(last.end)}. Es la última comparación evaluable.</p> : <p>Hay {q.eligibleDays} días después de la referencia, pero aún no cuatro pares comparables en un periodo de al menos 14 días.</p>}
            <p>{q.state === 'repeated' ? 'La dirección y el tamaño de la diferencia son parecidos en dos periodos separados. La asociación sigue siendo exploratoria y puede depender de factores no registrados.' : q.state === 'first_signal' ? 'Hay una primera diferencia. Falta comprobarla con fechas nuevas en otro periodo.' : q.state === 'inconsistent' ? 'La diferencia cambia entre periodos. Esta historia no sostiene todavía una relación estable.' : q.state === 'no_difference' ? 'Las comparaciones no muestran una diferencia sostenida. No permite descartar otras relaciones.' : 'La pregunta sigue abierta mientras llegan días comparables.'}</p>
          </>}
          </details>
          {!!q.excludedContext && <small>{q.excludedContext} días candidatos apartados por enfermedad o viaje registrado, incluyendo el día posterior.</small>}
          <details><summary>Ver fechas, pares y condiciones de la comparación</summary><p>Grupos inferior (≤ referencia) y superior (&gt; referencia), con una referencia fijada antes de evaluar resultados. Emparejamos sin reutilizar días, a no más de 14 días de distancia y dentro del mismo tipo de día (lunes–viernes o sábado–domingo) y con la misma zona horaria cuando está registrada. Para las dos primeras preguntas se exige una duración de sueño previa a no más de 60 min de diferencia. Cuando ambos días tienen pasos previos o estrés registrado, también se comprueba un contexto parecido. La ausencia de un evento no se interpreta como ausencia de exposición.</p><p>Periodos de 28 días sin solapar; un periodo en curso necesita al menos 14 días y cuatro pares. La diferencia es la mediana de las diferencias dentro de cada pareja. Para llamarla repetida, la dirección debe coincidir y el tamaño no puede variar más del doble en los dos últimos periodos evaluables. Son reglas exploratorias del producto, no umbrales clínicos ni una prueba de causalidad. La dependencia entre días puede persistir.</p>
            <div className="weeklyEvidence">{q.blocks.map(block => <div key={block.start}><h4>{dateLabel(block.start)} – {dateLabel(block.end)} · {block.complete ? 'periodo cerrado' : 'periodo en curso'}</h4><p>{block.candidates} días candidatos · {block.matches.length} pares · {block.delta === null ? 'cobertura insuficiente' : deltaLabel(q.y, block.delta)}</p><table><thead><tr><th>Día del grupo inferior</th><th>Día del superior</th><th>{signalLabel(q.y)} inferior / superior</th></tr></thead><tbody>{block.matches.map(pair => <tr key={`${pair.lower.date}|${pair.higher.date}`}><td>{pair.lower.date}<small>Contexto: {pair.lower.exposureDates.join(', ')}</small></td><td>{pair.higher.date}<small>Contexto: {pair.higher.exposureDates.join(', ')}</small></td><td>{formatMonitoring(q.y, pair.lower.y)} / {formatMonitoring(q.y, pair.higher.y)}</td></tr>)}</tbody></table></div>)}</div>
          </details>
          <details><summary>Memoria de esta pregunta · {history.length} {history.length === 1 ? 'revisión' : 'revisiones'}</summary><p>Una semana puede tener varias revisiones si cambian sus datos o contexto. Esas revisiones no cuentan como nuevas repeticiones.</p>{history.length ? history.map(m => <p key={m.id}><b>Semana hasta {dateLabel(m.weekEnd)}:</b> {QUESTION_STATES[m.state]} · {m.pairs} pares en la última comparación. <small>Guardada el {new Date(m.recordedAt).toLocaleString('es-ES')}.</small></p>) : <p>Todavía no hay revisiones guardadas de esta pregunta. Las lecturas históricas recalculadas no se presentan como conclusiones que ya conocíamos entonces.</p>}</details>
          {onOpenTrend && <button onClick={() => onOpenTrend(q.y)}>Explorar {signalLabel(q.y).toLowerCase()} →</button>}
        </article>;
      })}
    </section>

    <section className="card weeklyContext" aria-label="Contexto de la semana"><h2>Qué ocurría alrededor</h2><p>{report.events.length} {report.events.length === 1 ? 'evento registrado' : 'eventos registrados'} · {report.checkIns.length}/7 días con check-in. Lo que no se registró sigue siendo desconocido.</p>
      {report.events.map(e => <div className="weeklyEvent" key={e.id}><time>{dateLabel(e.date)}</time><div><strong>{contextLabel(e.type)}</strong>{e.note && <p>{e.note}</p>}</div></div>)}
      {report.checkIns.map(c => <div className="weeklyEvent" key={c.id}><time>{dateLabel(c.date)}</time><span>{[['Energía', c.energy], ['Estrés', c.stress], ['Fatiga', c.fatigue]].filter(([, value]) => value !== null).map(([label, value]) => `${label}: ${value}/5`).join(' · ')}</span></div>)}
      {onAddContext && <button onClick={() => onAddContext(report.end)}>Añadir contexto de esta semana</button>}
    </section>
  </div>;
}
